/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gestion Ressources</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.GestionRessources#getQuantite <em>Quantite</em>}</li>
 *   <li>{@link fr.n7.pDL1.GestionRessources#getRessources <em>Ressources</em>}</li>
 *   <li>{@link fr.n7.pDL1.GestionRessources#isUtilisee <em>Utilisee</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getGestionRessources()
 * @model
 * @generated
 */
public interface GestionRessources extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantite</em>' attribute.
   * @see #setQuantite(int)
   * @see fr.n7.pDL1.PDL1Package#getGestionRessources_Quantite()
   * @model
   * @generated
   */
  int getQuantite();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.GestionRessources#getQuantite <em>Quantite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantite</em>' attribute.
   * @see #getQuantite()
   * @generated
   */
  void setQuantite(int value);

  /**
   * Returns the value of the '<em><b>Ressources</b></em>' reference list.
   * The list contents are of type {@link fr.n7.pDL1.Ressource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressources</em>' reference list.
   * @see fr.n7.pDL1.PDL1Package#getGestionRessources_Ressources()
   * @model
   * @generated
   */
  EList<Ressource> getRessources();

  /**
   * Returns the value of the '<em><b>Utilisee</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Utilisee</em>' attribute.
   * @see #setUtilisee(boolean)
   * @see fr.n7.pDL1.PDL1Package#getGestionRessources_Utilisee()
   * @model
   * @generated
   */
  boolean isUtilisee();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.GestionRessources#isUtilisee <em>Utilisee</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Utilisee</em>' attribute.
   * @see #isUtilisee()
   * @generated
   */
  void setUtilisee(boolean value);

} // GestionRessources
