/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.ProcessElement#getProcess <em>Process</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getProcessElement()
 * @model
 * @generated
 */
public interface ProcessElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Process</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process</em>' reference.
   * @see #setProcess(fr.n7.pDL1.Process)
   * @see fr.n7.pDL1.PDL1Package#getProcessElement_Process()
   * @model
   * @generated
   */
  fr.n7.pDL1.Process getProcess();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.ProcessElement#getProcess <em>Process</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Process</em>' reference.
   * @see #getProcess()
   * @generated
   */
  void setProcess(fr.n7.pDL1.Process value);

} // ProcessElement
