/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.WorkDefinition#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.pDL1.WorkDefinition#getGestionressource <em>Gestionressource</em>}</li>
 *   <li>{@link fr.n7.pDL1.WorkDefinition#getLinksToPredecessors <em>Links To Predecessors</em>}</li>
 *   <li>{@link fr.n7.pDL1.WorkDefinition#getLinksToSuccessors <em>Links To Successors</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getWorkDefinition()
 * @model
 * @generated
 */
public interface WorkDefinition extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.pDL1.PDL1Package#getWorkDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.WorkDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Gestionressource</b></em>' reference list.
   * The list contents are of type {@link fr.n7.pDL1.GestionRessources}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gestionressource</em>' reference list.
   * @see fr.n7.pDL1.PDL1Package#getWorkDefinition_Gestionressource()
   * @model
   * @generated
   */
  EList<GestionRessources> getGestionressource();

  /**
   * Returns the value of the '<em><b>Links To Predecessors</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links To Predecessors</em>' reference.
   * @see #setLinksToPredecessors(WorkSequence)
   * @see fr.n7.pDL1.PDL1Package#getWorkDefinition_LinksToPredecessors()
   * @model
   * @generated
   */
  WorkSequence getLinksToPredecessors();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.WorkDefinition#getLinksToPredecessors <em>Links To Predecessors</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Links To Predecessors</em>' reference.
   * @see #getLinksToPredecessors()
   * @generated
   */
  void setLinksToPredecessors(WorkSequence value);

  /**
   * Returns the value of the '<em><b>Links To Successors</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links To Successors</em>' reference.
   * @see #setLinksToSuccessors(WorkSequence)
   * @see fr.n7.pDL1.PDL1Package#getWorkDefinition_LinksToSuccessors()
   * @model
   * @generated
   */
  WorkSequence getLinksToSuccessors();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.WorkDefinition#getLinksToSuccessors <em>Links To Successors</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Links To Successors</em>' reference.
   * @see #getLinksToSuccessors()
   * @generated
   */
  void setLinksToSuccessors(WorkSequence value);

} // WorkDefinition
